apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: azure-keyvault
spec:
  provider:
    azurekv:
      authType: ManagedIdentity
      identityId: "${AKS_KUBELET_IDENTITY_CLIENT_ID}"
      vaultUrl: "https://${KEYVAULT_NAME}.vault.azure.net"
      tenantId: "${AZURE_TENANT_ID}"
