apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: nessie-secrets
  namespace: nessie
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "${AKS_KUBELET_IDENTITY_CLIENT_ID}"
    keyvaultName: "${KEYVAULT_NAME}"
    objects: |
      array:
        - |
          objectName: nessie-jdbc-url
          objectType: secret
        - |
          objectName: postgres-admin-password
          objectType: secret
    tenantId: "${AZURE_TENANT_ID}"
  secretObjects:
    - secretName: nessie-secrets
      type: Opaque
      data:
        - objectName: nessie-jdbc-url
          key: jdbc-url
        - objectName: postgres-admin-password
          key: db-password
