apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nessie-secrets
  namespace: nessie
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azure-keyvault
  target:
    name: nessie-secrets
    creationPolicy: Owner
  data:
    - secretKey: jdbc-url
      remoteRef:
        key: nessie-jdbc-url
    - secretKey: db-password
      remoteRef:
        key: postgres-admin-password
