apiVersion: v1
kind: Pod
metadata:
  name: secret-init
  namespace: ${SVC}
spec:
  restartPolicy: Never
  containers:
  - name: init
    image: busybox:stable
    command: ["sh", "-c", "echo secrets mounted"]
    volumeMounts:
    - name: secrets
      mountPath: /mnt/secrets
  volumes:
  - name: secrets
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: ${SVC}-secrets
